name: Build APK
on: 
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Build with Buildozer
      uses: digreatb/buildozer-action@v2
      with:
        buildozer-cmd: buildozer android debug
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: NemazApp-APK
        path: bin/*.apk
